from copy import deepcopy
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import os

from src.environment import BulletChessEnv



class AlphaZeroNet(nn.Module):
    def __init__(self, in_channels=15, n_actions=4096):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv2d(128, 128, kernel_size=3, padding=1),
            nn.ReLU(),
        )
        self.fc = nn.Flatten()

        # Policy head
        self.policy = nn.Sequential(
            nn.Linear(128 * 8 * 8, 1024),
            nn.ReLU(),
            nn.Linear(1024, n_actions)
        )

        # Value head
        self.value = nn.Sequential(
            nn.Linear(128 * 8 * 8, 512),
            nn.ReLU(),
            nn.Linear(512, 1),
            nn.Tanh()
        )

    def forward(self, x):
        x = self.conv(x)
        x = self.fc(x)
        policy_logits = self.policy(x)
        value = self.value(x)
        return policy_logits, value.squeeze(-1)
    
"""
MCTS (Monte Carlo Tree Search)
"""

class MCTSNode:
    def __init__(self, prior, parent=None):
        self.prior = prior
        self.parent = parent
        self.children = {}
        self.visit_count = 0
        self.value_sum = 0.0

    def value(self):
        return self.value_sum / self.visit_count if self.visit_count else 0

    def ucb_score(self, c_puct):
        return self.value() + c_puct * self.prior * np.sqrt(self.parent.visit_count) / (1 + self.visit_count)
    


class MCTS:
    def __init__(self, model, env: BulletChessEnv, n_simulations=800, c_puct=1.5, device=None):
        self.model = model
        self.env = env
        self.n_simulations = n_simulations
        self.c_puct = c_puct
        self.device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def run(self) -> np.ndarray:
        root = MCTSNode(prior=1.0)
        for _ in range(self.n_simulations):
            node = root
            scratch_env = deepcopy(self.env)

            # Selection
            while node.children:
                max_ucb = -float("inf")
                best_action = None
                for action, child in node.children.items():
                    ucb = child.ucb_score(self.c_puct)
                    if ucb > max_ucb:
                        max_ucb = ucb
                        best_action = action
                node = node.children[best_action]
                _, _, done, _ = scratch_env.step(best_action)
                if done:
                    break

            # Expansion
            obs = scratch_env.get_observation()
            obs_tensor = torch.tensor(obs).permute(2, 0, 1).unsqueeze(0).float().to(self.device)
            policy_logits, value = self.model(obs_tensor)
            policy = F.softmax(policy_logits, dim=1).squeeze(0).detach().cpu().numpy()

            legal_actions = scratch_env.get_legal_actions()
            for action in legal_actions:
                if action not in node.children:
                    node.children[action] = MCTSNode(prior=policy[action], parent=node)

            # Backpropagation
            backup = node
            while backup:
                backup.visit_count += 1
                backup.value_sum += value.item()
                backup = backup.parent

        # Collect visit counts for the root node's children
        pi = np.zeros(4096)
        legal_actions = self.env.get_legal_actions()
        visit_counts = np.array([root.children[a].visit_count if a in root.children else 0 for a in legal_actions])

        if visit_counts.sum() == 0:
            print("WARNING: visit_counts all zero. Using uniform policy.")
            for a in legal_actions:
                pi[a] = 1.0
        else:
            normed = visit_counts / visit_counts.sum()
            for i, a in enumerate(legal_actions):
                pi[a] = normed[i]

        pi_sum = pi.sum()
        if pi_sum == 0.0:
            print(f"WARNING: pi is zero vector. Using uniform policy.")
            for a in legal_actions:
                pi[a] = 1.0
            pi_sum = pi.sum()

        pi /= pi_sum

        assert not np.isnan(pi).any(), "pi contains NaNs!"
        assert abs(pi.sum() - 1.0) < 1e-5, f"pi does not sum to 1: {pi.sum()}"

        return pi



class MCTSAgent:
    """
    Policy-Value Agent with Alpha-zero style training.
    No epsilon-greedy or target networks.
    Uses MCTS for action selection and AlphaZeroNet for policy and value estimation.

    This agent is designed to be used with a BulletChessEnv environment.
    It runs MCTS to select actions based on the policy distribution generated by the AlphaZeroNet
    and trains the model using examples collected from self-play games.
    The agent does not use epsilon-greedy exploration or target networks, relying solely on MCTS for action selection.
    The training process involves optimizing the model on a set of (state, policy, value) tuples collected during self-play games.
    The agent can save and load its state, allowing for easy checkpointing and resuming of training.
    It is designed to be flexible and can be configured with different hyperparameters such as learning rate and MCTS parameters.
    The agent's architecture consists of a convolutional neural network (AlphaZeroNet) that outputs both policy and value estimates.

    Attributes:
        model (AlphaZeroNet): The neural network model used for policy and value estimation.
        cfg (dict): Configuration dictionary containing hyperparameters for the agent.
        env (BulletChessEnv): The environment in which the agent operates.
        device (torch.device): The device on which the model is trained and evaluated (CPU or GPU).
        optimizer (torch.optim.Optimizer): The optimizer used for training the model.
    Methods:
        select_action_from_pi(pi, temperature=1.0): Selects an action based on
            the policy distribution `pi` and a temperature parameter.
        run_mcts(env): Runs MCTS on the current environment state and returns action probabilities.
        train_step(examples, optimizer, epochs=1): Trains the model on a list of (state, policy, value) tuples.
        save(path: str): Saves the agent's model and optimizer state to a file.
        load(path: str): Loads the agent's model and optimizer state from a file.
        get_pi()
    Usage:
        agent = MCTSAgent(cfg, env)
        action_probs = agent.run_mcts(env)
        action = agent.select_action_from_pi(action_probs, temperature=1.0)
        agent.train_step(examples, agent.optimizer, epochs=10)
        agent.save("path/to/save/model.pth")
        agent.load("path/to/save/model.pth")
    """

    def __init__(self, cfg: dict, env: BulletChessEnv, device=None):
        """
        Initializes the MCTSAgent with a configuration dictionary and a BulletChessEnv environment.
        Args:
            cfg (dict): Configuration dictionary containing hyperparameters for the agent.
            env (BulletChessEnv): The environment in which the agent operates.
            device (torch.device, optional): The device on which the model will be trained and evaluated.
                Defaults to "cuda" if available, otherwise "cpu".

        Initializes the MCTSAgent with the given configuration and environment.
        This method sets up the neural network model, optimizer, and device for training and evaluation.
        """
        self.device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = AlphaZeroNet().to(self.device)

        self.cfg = cfg
        self.env = env

        lr = cfg["agent"]["lr"]
        self.optimizer = torch.optim.Adam(self.model.parameters(), lr=lr)
      
    def select_action_from_pi(self, pi, temperature=1.0):
        """
        Selects an action based on the policy distribution `pi` and a temperature parameter.
        Args:
            pi (np.ndarray): The policy distribution from which to sample actions.
            temperature (float): The temperature parameter for action selection.
        Returns:
            int: The selected action index.
        
        If temperature is 0, the action with the highest probability is selected.
        If temperature is greater than 0, actions are sampled from the policy distribution `pi`
        using a softmax distribution adjusted by the temperature.
        The higher the temperature, the more uniform the action selection becomes.
        """
        temperature = self.cfg["mcts"]["temperature"]
        legal_actions = self.env.get_legal_actions()

        pi_filtered = np.array([pi[a] for a in legal_actions])
        
        if pi_filtered.sum() == 0:
            print("WARNING: Filtered π is zero vector. Sampling uniformly from legal actions.")
            probs = np.ones(len(legal_actions)) / len(legal_actions)
        else:
            probs = pi_filtered / pi_filtered.sum()

        if temperature == 0:
            best_index = np.argmax(probs)
            action = legal_actions[best_index]
        else:
            action = np.random.choice(legal_actions, p=probs)

        assert action in legal_actions, f"Selected illegal action: {action}"
        return action

    def run_mcts(self, env):
        """
        Runs MCTS on the current environment state and returns action probabilities.
        Args:
            env (BulletChessEnv): The environment in which to run MCTS.
        Returns:
            np.ndarray: The action probabilities from MCTS.

        This method initializes an MCTS instance with the current model and environment,
        and runs the MCTS algorithm to obtain action probabilities.
        It uses the configuration parameters for the number of simulations and exploration constant.
        The MCTS algorithm simulates multiple games from the current state, exploring the most promising actions
        based on the policy distribution generated by the model.
        """

        mcts = MCTS(
            model=self.model,
            env=deepcopy(env),
            n_simulations = self.cfg["mcts"]["mcts_simulations"],
            c_puct = self.cfg["mcts"]["c_puct"],
            device=self.device
        )
        return mcts.run()


    def train_step(self, examples, epochs=1):
        """
        Trains the model on a list of (state, policy, value) tuples.
        Args:
            examples (list): A list of tuples containing (state, policy, value).
            optimizer (torch.optim.Optimizer): The optimizer to use for training.
            epochs (int): The number of training epochs to run.
        Returns:
            float: The loss value after training.

        This method performs a training step on the model using the provided examples.
        It converts the examples into tensors, permutes the dimensions to match the model's input requirements
        and computes the policy and value predictions from the model.
        The loss is calculated as the sum of the policy loss (cross-entropy between MCTS probabilities and predicted policy)
        and the value loss (mean squared error between predicted and actual game outcome).
        The optimizer is used to update the model parameters based on the computed loss.
        The method runs for a specified number of epochs, allowing the model to learn from the provided examples.
        The loss is returned as a float value.
        """

        optimizer = self.optimizer
        self.model.train()
        for _ in range(epochs):
            states, policies, values = zip(*examples)

            states = np.array(states)
            policies = np.array(policies)
            values = np.array([np.sign(v) for v in values])  # normalize target

            states = torch.tensor(states, dtype=torch.float32, device=self.device)
            states = states.permute(0, 3, 1, 2).contiguous()
            policies = torch.tensor(policies, dtype=torch.float32, device=self.device)
            values = torch.tensor(values, dtype=torch.float32, device=self.device)

            pred_policy, pred_value = self.model(states)

            # Correct policy loss (KL divergence-style)
            log_probs = F.log_softmax(pred_policy, dim=1)
            policy_loss = -torch.sum(policies * log_probs, dim=1).mean()

            # Correct MSE value loss with normalized target
            value_loss = F.mse_loss(pred_value.squeeze(), values)
            loss = policy_loss + value_loss

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
        return loss.item()

    
    def save(self, path: str):
      """Save agent state to file
      Args:
          path (str): The file path where the agent state will be saved.
          
        This method saves the model's state dictionary and optimizer's state dictionary to the specified path.
        It creates the necessary directories if they do not exist and uses `torch.save` to serialize the model and optimizer states.
        The saved file can later be loaded to restore the agent's state for further training or evaluation
        """
      os.makedirs(os.path.dirname(path), exist_ok=True)
      torch.save({
          "model": self.model.state_dict(),
          "optim": self.optimizer.state_dict()
      }, path)

    def load(self, path: str):
      """Load agent state from file
      Args:
          path (str): The file path from which the agent state will be loaded.

        This method loads the model's state dictionary and optimizer's state dictionary from the specified path.
        It uses `torch.load` to deserialize the model and optimizer states, and then applies them to the model and optimizer.
        It is important to ensure that the model architecture matches the one used when saving the state.
      """
      ckpt = torch.load(path, map_location=self.device)
      self.model.load_state_dict(ckpt["model"])
      self.optimizer.load_state_dict(ckpt["optim"])

    def get_pi(self):
        """Get the current policy distribution (pi) from the model.
        Returns:
            np.ndarray: The current policy distribution (pi) from the model.
        """
        return getattr(self, "pi", None)


def load_mcts_from_path(path, cfg, env):
    """Load MCTS agent from a file path.
    Args:
        path (str): The file path to load the agent from.
        cfg (dict): The configuration dictionary for the agent.
        env (Environment): The environment instance for the agent.
    Returns:
        MCTSAgent: The loaded MCTS agent.
    """
    agent = MCTSAgent(cfg, env)
    agent.load(path)
    return agent
